config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'static_pages/home'
  get 'static_pages/project'
  get 'static_pages/team'
  get 'static_pages/blog'
  get 'static_pages/shop'
  get 'static_pages/privacy'
  get 'static_pages/b2b'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def project
  end

  def team
  end

  def blog
  end

  def shop
  end

  def privacy
  end

  def b2b
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodtest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div >
    <%= render 'header' %>
      <div class="container"> 
        <%= yield %> 
      </div>
    <%= render 'footer' %>
    </div>
  </body>
</html>

app/views/static_pages/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light" style="background-color: #6c757d">
  <div class="container-fluid">
    <%= link_to "Privacy", static_pages_privacy_path, class: "nav-link" %>
    <a class="nav-link" href="#">Contatti</a>
    
  </div>
</nav>

app/views/static_pages/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark py-5">
    <div class="container-fluid">
        <a class="navbar-brand d-flex w-50 " href="http://www.foodissey.it">Foodissey</a>
        <div class="collapse navbar-collapse w-100" id="navbarSupportedContent">
            <div class="nav navbar-nav  w-100 flex-grow-1 justify-content-end">
                <%= link_to "Home", static_pages_home_path, class: "nav-link ms-3 me-2", 'aria-current': "page" %>
                <%= link_to "Il Progetto", static_pages_project_path, class: "nav-link " %>
                <%= link_to "Chi Siamo", static_pages_team_path, class: "nav-link ms-3 me-2" %>
                <%= link_to "Blog", static_pages_blog_path, class: "nav-link ms-3 me-2" %>
                <%= link_to "Shop", static_pages_shop_path, class: "nav-link ms-3 me-2" %>
                <%= link_to "Regalistica Aziendale", static_pages_b2b_path, class: "nav-link " %>
                <%= link_to "Login", '#', class: "nav-link " %>
            </div>   
            </div>
    </div>
</nav>

app/views/static_pages/b2b.html.erb
<h1>StaticPages#b2b</h1>
<p>Find me in app/views/static_pages/b2b.html.erb</p>

app/views/static_pages/blog.html.erb
<h1>StaticPages#blog</h1>
<p>Find me in app/views/static_pages/blog.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/project.html.erb
<h1>StaticPages#project</h1>
<p>Find me in app/views/static_pages/project.html.erb</p>

app/views/static_pages/shop.html.erb
<h1>StaticPages#shop</h1>
<p>Find me in app/views/static_pages/shop.html.erb</p>

app/views/static_pages/team.html.erb
<h1>StaticPages#team</h1>
<p>Find me in app/views/static_pages/team.html.erb</p>